# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core/app/proxyman/command/command.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'core/app/proxyman/command/command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.protocol import user_pb2 as common_dot_protocol_dot_user__pb2
from common.serial import typed_message_pb2 as common_dot_serial_dot_typed__message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'core/app/proxyman/command/command.proto\x12\x19xray.app.proxyman.command\x1a\x1a\x63ommon/protocol/user.proto\x1a!common/serial/typed_message.proto\"<\n\x10\x41\x64\x64UserOperation\x12(\n\x04user\x18\x01 \x01(\x0b\x32\x1a.xray.common.protocol.User\"$\n\x13RemoveUserOperation\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"6\n\x11\x41\x64\x64InboundRequest\x12!\n\x19\x64ummy_inbound_placeholder\x18\x01 \x01(\t\"\x14\n\x12\x41\x64\x64InboundResponse\"#\n\x14RemoveInboundRequest\x12\x0b\n\x03tag\x18\x01 \x01(\t\"\x17\n\x15RemoveInboundResponse\"W\n\x13\x41lterInboundRequest\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x33\n\toperation\x18\x02 \x01(\x0b\x32 .xray.common.serial.TypedMessage\"\x16\n\x14\x41lterInboundResponse\"3\n\x15GetInboundUserRequest\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"C\n\x16GetInboundUserResponse\x12)\n\x05users\x18\x01 \x03(\x0b\x32\x1a.xray.common.protocol.User\"-\n\x1cGetInboundUsersCountResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\x32\xe6\x04\n\x0eHandlerService\x12k\n\nAddInbound\x12,.xray.app.proxyman.command.AddInboundRequest\x1a-.xray.app.proxyman.command.AddInboundResponse\"\x00\x12t\n\rRemoveInbound\x12/.xray.app.proxyman.command.RemoveInboundRequest\x1a\x30.xray.app.proxyman.command.RemoveInboundResponse\"\x00\x12q\n\x0c\x41lterInbound\x12..xray.app.proxyman.command.AlterInboundRequest\x1a/.xray.app.proxyman.command.AlterInboundResponse\"\x00\x12x\n\x0fGetInboundUsers\x12\x30.xray.app.proxyman.command.GetInboundUserRequest\x1a\x31.xray.app.proxyman.command.GetInboundUserResponse\"\x00\x12\x83\x01\n\x14GetInboundUsersCount\x12\x30.xray.app.proxyman.command.GetInboundUserRequest\x1a\x37.xray.app.proxyman.command.GetInboundUsersCountResponse\"\x00\x42m\n\x1d\x63om.xray.app.proxyman.commandP\x01Z.github.com/xtls/xray-core/app/proxyman/command\xaa\x02\x19Xray.App.Proxyman.Commandb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.app.proxyman.command.command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035com.xray.app.proxyman.commandP\001Z.github.com/xtls/xray-core/app/proxyman/command\252\002\031Xray.App.Proxyman.Command'
  _globals['_ADDUSEROPERATION']._serialized_start=133
  _globals['_ADDUSEROPERATION']._serialized_end=193
  _globals['_REMOVEUSEROPERATION']._serialized_start=195
  _globals['_REMOVEUSEROPERATION']._serialized_end=231
  _globals['_ADDINBOUNDREQUEST']._serialized_start=233
  _globals['_ADDINBOUNDREQUEST']._serialized_end=287
  _globals['_ADDINBOUNDRESPONSE']._serialized_start=289
  _globals['_ADDINBOUNDRESPONSE']._serialized_end=309
  _globals['_REMOVEINBOUNDREQUEST']._serialized_start=311
  _globals['_REMOVEINBOUNDREQUEST']._serialized_end=346
  _globals['_REMOVEINBOUNDRESPONSE']._serialized_start=348
  _globals['_REMOVEINBOUNDRESPONSE']._serialized_end=371
  _globals['_ALTERINBOUNDREQUEST']._serialized_start=373
  _globals['_ALTERINBOUNDREQUEST']._serialized_end=460
  _globals['_ALTERINBOUNDRESPONSE']._serialized_start=462
  _globals['_ALTERINBOUNDRESPONSE']._serialized_end=484
  _globals['_GETINBOUNDUSERREQUEST']._serialized_start=486
  _globals['_GETINBOUNDUSERREQUEST']._serialized_end=537
  _globals['_GETINBOUNDUSERRESPONSE']._serialized_start=539
  _globals['_GETINBOUNDUSERRESPONSE']._serialized_end=606
  _globals['_GETINBOUNDUSERSCOUNTRESPONSE']._serialized_start=608
  _globals['_GETINBOUNDUSERSCOUNTRESPONSE']._serialized_end=653
  _globals['_HANDLERSERVICE']._serialized_start=656
  _globals['_HANDLERSERVICE']._serialized_end=1270
# @@protoc_insertion_point(module_scope)
