# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core/app/stats/command/command.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'core/app/stats/command/command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$core/app/stats/command/command.proto\x12\x16xray.app.stats.command\".\n\x0fGetStatsRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05reset\x18\x02 \x01(\x08\"#\n\x04Stat\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03\">\n\x10GetStatsResponse\x12*\n\x04stat\x18\x01 \x01(\x0b\x32\x1c.xray.app.stats.command.Stat\"3\n\x11QueryStatsRequest\x12\x0f\n\x07pattern\x18\x01 \x01(\t\x12\r\n\x05reset\x18\x02 \x01(\x08\"@\n\x12QueryStatsResponse\x12*\n\x04stat\x18\x01 \x03(\x0b\x32\x1c.xray.app.stats.command.Stat\"\x11\n\x0fSysStatsRequest\"\xc2\x01\n\x10SysStatsResponse\x12\x14\n\x0cNumGoroutine\x18\x01 \x01(\r\x12\r\n\x05NumGC\x18\x02 \x01(\r\x12\r\n\x05\x41lloc\x18\x03 \x01(\x04\x12\x12\n\nTotalAlloc\x18\x04 \x01(\x04\x12\x0b\n\x03Sys\x18\x05 \x01(\x04\x12\x0f\n\x07Mallocs\x18\x06 \x01(\x04\x12\r\n\x05\x46rees\x18\x07 \x01(\x04\x12\x13\n\x0bLiveObjects\x18\x08 \x01(\x04\x12\x14\n\x0cPauseTotalNs\x18\t \x01(\x04\x12\x0e\n\x06Uptime\x18\n \x01(\r\"\xa4\x01\n\x1cGetStatsOnlineIpListResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12J\n\x03ips\x18\x02 \x03(\x0b\x32=.xray.app.stats.command.GetStatsOnlineIpListResponse.IpsEntry\x1a*\n\x08IpsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x32\xb3\x03\n\x0cStatsService\x12_\n\x08GetStats\x12\'.xray.app.stats.command.GetStatsRequest\x1a(.xray.app.stats.command.GetStatsResponse\"\x00\x12\x65\n\nQueryStats\x12).xray.app.stats.command.QueryStatsRequest\x1a*.xray.app.stats.command.QueryStatsResponse\"\x00\x12\x62\n\x0bGetSysStats\x12\'.xray.app.stats.command.SysStatsRequest\x1a(.xray.app.stats.command.SysStatsResponse\"\x00\x12w\n\x14GetStatsOnlineIpList\x12\'.xray.app.stats.command.GetStatsRequest\x1a\x34.xray.app.stats.command.GetStatsOnlineIpListResponse\"\x00\x42\x64\n\x1a\x63om.xray.app.stats.commandP\x01Z+github.com/xtls/xray-core/app/stats/command\xaa\x02\x16Xray.App.Stats.Commandb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.app.stats.command.command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.xray.app.stats.commandP\001Z+github.com/xtls/xray-core/app/stats/command\252\002\026Xray.App.Stats.Command'
  _globals['_GETSTATSONLINEIPLISTRESPONSE_IPSENTRY']._loaded_options = None
  _globals['_GETSTATSONLINEIPLISTRESPONSE_IPSENTRY']._serialized_options = b'8\001'
  _globals['_GETSTATSREQUEST']._serialized_start=64
  _globals['_GETSTATSREQUEST']._serialized_end=110
  _globals['_STAT']._serialized_start=112
  _globals['_STAT']._serialized_end=147
  _globals['_GETSTATSRESPONSE']._serialized_start=149
  _globals['_GETSTATSRESPONSE']._serialized_end=211
  _globals['_QUERYSTATSREQUEST']._serialized_start=213
  _globals['_QUERYSTATSREQUEST']._serialized_end=264
  _globals['_QUERYSTATSRESPONSE']._serialized_start=266
  _globals['_QUERYSTATSRESPONSE']._serialized_end=330
  _globals['_SYSSTATSREQUEST']._serialized_start=332
  _globals['_SYSSTATSREQUEST']._serialized_end=349
  _globals['_SYSSTATSRESPONSE']._serialized_start=352
  _globals['_SYSSTATSRESPONSE']._serialized_end=546
  _globals['_GETSTATSONLINEIPLISTRESPONSE']._serialized_start=549
  _globals['_GETSTATSONLINEIPLISTRESPONSE']._serialized_end=713
  _globals['_GETSTATSONLINEIPLISTRESPONSE_IPSENTRY']._serialized_start=671
  _globals['_GETSTATSONLINEIPLISTRESPONSE_IPSENTRY']._serialized_end=713
  _globals['_STATSSERVICE']._serialized_start=716
  _globals['_STATSSERVICE']._serialized_end=1151
# @@protoc_insertion_point(module_scope)
